/**
 * Lock: tripSettlementDbColumns() may only emit real public.trips columns.
 *
 * Authoritative snapshot: production thazislrdkjpvvghtvzo information_schema
 * 2026-08-18 (MK-260818-002 audit). No provider_fee_amount column exists.
 *
 * Run:
 *   deno test --allow-read supabase/functions/_shared/tripSettlementDbColumnsLock.test.ts
 */
import { assertEquals } from "https://deno.land/std@0.224.0/assert/mod.ts";
import {
  calculateTripSettlement,
  tripSettlementDbColumns,
} from "./tripSettlement.ts";

/** Frozen production public.trips column names (2026-08-18). */
const AUTHORITATIVE_PRODUCTION_TRIPS_COLUMNS = new Set<string>([
  "accepted_commission_percent",
  "accepted_dispatch_round",
  "accepted_dispatch_wave",
  "accepted_driver_offer_fare_pence",
  "accepted_preset_offer_fare_pence",
  "accepted_ride_offer_id",
  "airport_charge_pence",
  "applied_offer_code",
  "applied_offer_id",
  "applied_personal_voucher_code",
  "applied_personal_voucher_id",
  "arrival_cancellation_applied",
  "arrival_cancellation_applied_at",
  "arrival_cancellation_fee",
  "arrival_cancellation_reason",
  "arrived_at",
  "assigned_at",
  "authorised_amount_pence",
  "authorized_amount_pence",
  "base_fare_pence",
  "booking_source",
  "booking_type",
  "broadcast_enabled",
  "broadcast_started_at",
  "cancel_reason",
  "cancellation_fee_pence",
  "cancellation_grace_expires_at",
  "cancellation_note",
  "cancellation_reason",
  "cancelled_at",
  "cancelled_by",
  "cancelled_by_role",
  "cancelled_driver_ids",
  "capture_amount_pence",
  "cash_authorized_at",
  "cash_collected_at",
  "cash_collected_by_driver_id",
  "check_in_reminder_sent_at",
  "client_action_id",
  "commission_pct",
  "commission_pence",
  "commission_wallet_enabled",
  "commissionable_fare_pence",
  "commitment_time",
  "completed_at",
  "confirm_deadline_at",
  "confirmed_driver_id",
  "corporate_account_id",
  "created_at",
  "created_pricing_hash",
  "currency",
  "currency_code",
  "current_broadcast_round",
  "current_destination_index",
  "current_destination_type",
  "current_negotiation_id",
  "current_offer_driver_id",
  "current_offer_expires_at",
  "current_stop_id",
  "current_stop_index",
  "customer_modification_charge_pence",
  "debt_recovery_pence",
  "deferred_payment_method_id",
  "delivery_metadata",
  "delivery_type",
  "destination_change_adjustment_pence",
  "discount_pence",
  "discount_source",
  "dispatch_mode",
  "dispatch_status",
  "distance_unit",
  "driver_checked_in_at",
  "driver_confirm_deadline_at",
  "driver_id",
  "driver_location_lat",
  "driver_location_lng",
  "driver_net_amount",
  "driver_net_before_tip_pence",
  "driver_net_pence",
  "driver_passenger_compliments",
  "driver_passenger_feedback",
  "driver_passenger_low_rating_reasons",
  "driver_passenger_rating",
  "driver_passenger_rating_at",
  "driver_passenger_rating_skipped",
  "driver_passenger_rating_submitted",
  "driver_payment_confirmed_at",
  "driver_started_journey_to_pickup_at",
  "driver_tier_commission_percent",
  "driver_total_earnings_pence",
  "dropoff_address",
  "dropoff_latitude",
  "dropoff_longitude",
  "dropoff_zone_id",
  "escalation_status",
  "estimated_distance_km",
  "estimated_duration_minutes",
  "estimated_fare",
  "estimated_total_pence",
  "eta_risk_alert_sent_at",
  "excluded_driver_ids",
  "extras_pence",
  "fare",
  "fare_amount",
  "fare_breakdown",
  "fare_engine_config_id",
  "fare_locked",
  "fare_locked_at",
  "fare_revision_number",
  "fare_snapshot_json",
  "final_customer_fare_pence",
  "final_fare_pence",
  "final_payout_pence",
  "financial_model",
  "financial_outcome",
  "free_wait_expires_at",
  "grace_period_expired_at",
  "gross_fare_pence",
  "id",
  "idempotency_key",
  "invoice_delivery_eligible",
  "invoice_delivery_status",
  "invoice_email_error",
  "invoice_email_sent",
  "invoice_email_sent_at",
  "invoice_email_status",
  "invoice_generated_at",
  "invoice_no",
  "invoice_outstanding_pence",
  "invoice_paid_pence",
  "invoice_payment_classification",
  "invoice_payment_evidence_ids",
  "invoice_payment_evidence_source",
  "invoice_payment_resolved_at",
  "invoice_pdf_error",
  "invoice_pdf_path",
  "invoice_pdf_url",
  "invoice_provider_message_id",
  "invoice_recipient_email_snapshot",
  "invoice_recipient_user_id",
  "invoice_regenerated_at",
  "invoice_total_paid_pence",
  "is_scheduled",
  "job_type",
  "last_broadcast_at",
  "last_eta_calculated_at",
  "last_eta_minutes",
  "late_cancel_fee_pence",
  "locked_base_fare_pence",
  "locked_offer_type",
  "max_broadcast_rounds",
  "max_wave_commission_reduction_percent",
  "modification_confirmed_at",
  "modification_delta_pence",
  "modification_status",
  "modified_dropoff_address",
  "modified_dropoff_latitude",
  "modified_dropoff_longitude",
  "moving_away_alert_sent_at",
  "negotiation_allowed",
  "negotiation_disabled",
  "negotiation_locked_until",
  "negotiation_owner_driver_id",
  "negotiation_status",
  "no_driver_admin_alert_sent_at",
  "no_driver_customer_alert_sent_at",
  "no_show_by",
  "no_show_charge_pence",
  "not_moving_alert_sent_at",
  "offer_currency",
  "offer_discount_pence",
  "offer_snapshot",
  "onecab_net_pence",
  "original_dropoff_address",
  "original_dropoff_latitude",
  "original_dropoff_longitude",
  "original_payment_method",
  "other_pass_through_charges_pence",
  "outstanding_balance_pence",
  "paid_waiting_started_at",
  "passenger_id",
  "passenger_name",
  "passenger_phone",
  "payment_collection_model",
  "payment_coverage_status",
  "payment_deferred",
  "payment_hold_status",
  "payment_intent_id",
  "payment_intent_version",
  "payment_method",
  "payment_provider",
  "payment_reauth_at",
  "payment_reauth_status",
  "payment_session_id",
  "payment_state",
  "payment_status",
  "payment_type",
  "pickup_address",
  "pickup_arrived_at",
  "pickup_latitude",
  "pickup_longitude",
  "pickup_paid_waiting_started_at",
  "pickup_waiting_admin_config",
  "pickup_waiting_charge_pence",
  "pickup_waiting_chargeable_seconds",
  "pickup_waiting_finalized_at",
  "pickup_waiting_intervals_charged",
  "pickup_waiting_last_tick_at",
  "pickup_waiting_started_at",
  "pickup_zone_id",
  "platform_commission_amount",
  "platform_gross_revenue_pence",
  "platform_net_revenue_pence",
  "pre_assigned_driver_id",
  "preauth_buffer_pence",
  "previous_driver_id",
  "pricing_mode",
  "pricing_source",
  "pricing_version",
  "provider_available_on",
  "provider_charge_id",
  "provider_checkout_token",
  "provider_fee_pence",
  "provider_order_id",
  "provider_payment_id",
  "provider_payout_id",
  "provider_status",
  "provider_transfer_id",
  "provider_webhook_event_id",
  "quoted_fare_pence",
  "refund_amount_pence",
  "refund_reason",
  "refunded_at",
  "region_id",
  "scheduled_accepted_at",
  "scheduled_at",
  "scheduled_broadcast_at",
  "scheduled_committed_at",
  "scheduled_convert_at",
  "scheduled_driver_risk",
  "scheduled_status",
  "searching_expires_at",
  "sequence_no",
  "service_area_code",
  "service_area_id",
  "settlement_formula_version",
  "snapshotted_commission_currency",
  "snapshotted_commission_rate_bps",
  "special_instructions",
  "stack_position",
  "stacked_trip_id",
  "started_at",
  "status",
  "stop_arrived_at",
  "stop_charge_total_pence",
  "stop_waiting_charge_amount",
  "stop_waiting_charge_pence",
  "stop_waiting_finalized_at",
  "stop_waiting_free_seconds",
  "stop_waiting_paid_started_at",
  "stop_waiting_started_at",
  "stop_waiting_status",
  "stops",
  "surge_multiplier",
  "tip_amount_pence",
  "tip_pence",
  "tip_window_closed_at",
  "tip_window_expires_at",
  "total_authorized_amount_pence",
  "total_stops",
  "total_waiting_charge_pence",
  "trip_code",
  "trip_number",
  "trip_type",
  "trip_version",
  "updated_at",
  "vehicle_type",
  "vehicle_type_id",
  "voucher_discount_pence",
  "waiting_charge_pence",
  "waiting_minutes",
  "wallet_applied_pence",
  "wallet_balance_after",
  "wallet_balance_before",
]);

Deno.test("production trips schema has provider_fee_pence and not provider_fee_amount", () => {
  assertEquals(AUTHORITATIVE_PRODUCTION_TRIPS_COLUMNS.has("provider_fee_pence"), true);
  assertEquals(AUTHORITATIVE_PRODUCTION_TRIPS_COLUMNS.has("provider_fee_amount"), false);
});

Deno.test("tripSettlementDbColumns emits only real trips columns; no provider_fee_amount", () => {
  const stamp = tripSettlementDbColumns(calculateTripSettlement({
    final_fare_pence: 500,
    driver_tier_commission_percent: 15,
    provider_fee_pence: 10,
    provider_fee_confirmed: true,
  }));
  const keys = Object.keys(stamp);
  assertEquals(keys.includes("provider_fee_pence"), true);
  assertEquals(keys.includes("provider_fee_amount"), false);
  const invalid = keys.filter((k) => !AUTHORITATIVE_PRODUCTION_TRIPS_COLUMNS.has(k));
  assertEquals(invalid, []);
});

Deno.test("tripSettlementDbColumns source does not alias provider_fee_amount", async () => {
  const src = await Deno.readTextFile(new URL("./tripSettlement.ts", import.meta.url));
  const start = src.indexOf("export function tripSettlementDbColumns");
  const end = src.indexOf("export function mergeFareSnapshotSettlementJson");
  const fn = src.slice(start, end);
  assertEquals(fn.includes("provider_fee_amount"), false);
  assertEquals(fn.includes("provider_fee_pence"), true);
});
