-- Recovered from production (thazislrdkjpvvghtvzo). Provenance only — already deployed.
-- Observe-mode trigger: logs INTRODUCING illegal status/dispatch/assignment writes.
-- Never blocks trip writes.

CREATE TABLE IF NOT EXISTS public.trip_state_violations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  observed_at timestamptz NOT NULL DEFAULT now(),
  op text,
  trip_id uuid,
  trip_code text,
  old_status text,
  new_status text,
  dispatch_status text,
  confirmed_driver_id uuid,
  driver_id uuid,
  violation_type text,
  writer_application_name text,
  writer_role text,
  request_path text,
  txid bigint
);

CREATE OR REPLACE FUNCTION public.log_trip_state_violation()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
declare
  v_terminal boolean;
  v_active_dispatch boolean;
  v_cancel boolean;
  v_new_violates boolean;
  v_old_violates boolean;
  v_type text;
begin
  begin
    v_terminal := NEW.status in ('cancelled','customer_cancelled','expired','no_driver_found','no_show','completed');
    v_active_dispatch := lower(coalesce(NEW.dispatch_status,'')) in ('assigned','broadcasting','offering','offered','pending');
    v_cancel := NEW.status in ('cancelled','customer_cancelled','expired','no_driver_found');
    v_new_violates := (v_terminal and v_active_dispatch) or (v_cancel and NEW.confirmed_driver_id is not null);

    if v_new_violates then
      if TG_OP = 'INSERT' then
        v_old_violates := false;
      else
        v_old_violates :=
          (OLD.status in ('cancelled','customer_cancelled','expired','no_driver_found','no_show','completed')
             and lower(coalesce(OLD.dispatch_status,'')) in ('assigned','broadcasting','offering','offered','pending'))
          or (OLD.status in ('cancelled','customer_cancelled','expired','no_driver_found') and OLD.confirmed_driver_id is not null);
      end if;

      if not v_old_violates then
        v_type := case
          when (v_terminal and v_active_dispatch) and (v_cancel and NEW.confirmed_driver_id is not null) then 'I1+I2'
          when (v_terminal and v_active_dispatch) then 'I1'
          else 'I2' end;
        insert into public.trip_state_violations(
          op, trip_id, trip_code, old_status, new_status, dispatch_status,
          confirmed_driver_id, driver_id, violation_type,
          writer_application_name, writer_role, request_path, txid)
        values(
          TG_OP, NEW.id, NEW.trip_code,
          case when TG_OP='UPDATE' then OLD.status else null end,
          NEW.status, NEW.dispatch_status, NEW.confirmed_driver_id, NEW.driver_id, v_type,
          current_setting('application_name', true), current_user,
          current_setting('request.path', true), txid_current());
      end if;
    end if;
  exception when others then
    null;
  end;
  return null;
end;
$function$;

DROP TRIGGER IF EXISTS tr_observe_trip_state_violation ON public.trips;
CREATE TRIGGER tr_observe_trip_state_violation
  AFTER INSERT OR UPDATE ON public.trips
  FOR EACH ROW
  EXECUTE FUNCTION public.log_trip_state_violation();

COMMENT ON TABLE public.trip_state_violations IS
  'Observe-mode lifecycle invariant violations. Never blocks trip writes.';
COMMENT ON FUNCTION public.log_trip_state_violation() IS
  'AFTER INSERT/UPDATE trips: log introducing I1/I2 status/dispatch/assignment violations.';
