
ALTER TYPE payment_session_status ADD VALUE IF NOT EXISTS 'RECOVERY_CHECKOUT_CREATED';
ALTER TYPE payment_session_status ADD VALUE IF NOT EXISTS 'CUSTOMER_ACTION_REQUIRED';
ALTER TYPE payment_session_status ADD VALUE IF NOT EXISTS 'RECOVERY_COMPLETED';
ALTER TYPE payment_session_status ADD VALUE IF NOT EXISTS 'RECOVERY_DECLINED';
ALTER TYPE payment_session_status ADD VALUE IF NOT EXISTS 'RECOVERY_CANCELLED';
ALTER TYPE payment_session_status ADD VALUE IF NOT EXISTS 'RECOVERY_EXPIRED';
